### PR TITLE
Update for modern browsers

### PR DESCRIPTION
**Pull request by fregante**
Follows #9

### CODE REVIEW

**Comment by fregante** [comment]
Quick support question. Mocha seems to have gone nuts on my computer, it cached `index.js` somewhere and doesn't respond to changes to it. At all. Even if I empty the file the test result is always the same as it was earlier. Node is loading the correct file (because if I delete index.js it throws) but the tests don't change. :(

**Review by stefanbuck — APPROVED** [review]
Good stuff, will release a new version soon. Thanks for making all this changes

**Comment by stefanbuck** [comment]
Oh there's one remaining failing test. Can you please fix this

**Comment by fregante** [comment]
I can't because of the issue I described. The tests literally don't respond to my changes anymore, it seems 😕

**Comment by josephfrazier** [comment]
What happens if you remove node_modules and reinstall? If you have a globally installed version of mocha, you might want to remove it as well.

**Comment by stefanbuck** [comment]
Sorry, missed your comment. That's really strange, I can have a look later today

**Pull request closed without merging**
