### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by fregante**
Given that `global` is... global, I'm not sure of why it was implemented. I've never seen a module ask for the `global` variable.

### CODE REVIEW

**Comment by josephfrazier** [comment]
My best guess is that it was intended to allows usage in environment that aren't actually `global` (such as a [JSDOM](https://github.com/tmpvar/jsdom)), without having to override `global` beforehand. I'll let @stefanbuck weigh in, though.

**Comment by fregante** [comment]
If the issue is just testing, you can just add `global.document = jsdom(etc);`

https://github.com/sindresorhus/element-ready/blob/5427ac1/test.js#L7-L10

**Comment by fregante** [comment]
Not all commits are necessary, but if you're interested I can look into fixing the tests.

**Comment by stefanbuck** [comment]
Great cleanup @bfred-it and yes I'm interested in getting this merged 👍  Regarding the `global`, as @josephfrazier already mentioned it was implemented just for testing. I agree, this isn't a good pattern and we should get rid of it.

**Pull request closed without merging**
