### PR TITLE
Support pr page

### PR DESCRIPTION
**Pull request by gregberge**

### CODE REVIEW

**Comment by stefanbuck** [comment]
Looks good but could you please remove the `yarn.lock` file. Thanks

**Comment by gregberge** [comment]
@stefanbuck done

**Comment by stefanbuck** [comment]
The fixture that you attached, is this a page from github.com? I'm asking because my PR page looks a bit different also it doesn't contain the id `js-pjax-container`.

**Comment by gregberge** [comment]
Yes it's the pull request page from GitHub, not from a repo.

**Comment by stefanbuck** [comment]
I never noticed this link before 😉

**Comment by stefanbuck** [comment]
New version`0.3.0` is out.

**Comment by gregberge** [comment]
Thanks

**Pull request merged**
