### PR TITLE
allow setting `wait` option to `0`

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Btw, why is the default wait 250ms?

I'm using this in https://github.com/sindresorhus/refined-github

**Comment by stefanbuck** [comment]
If I remember correctly, there was a case when the callback was called multiple times. I have to check if this is still the case. The 250ms is a random picked number. Maybe we can get rid of the debounce at all.

**Comment by stefanbuck** [comment]
Looks like this is not an issue  anymore, so I can get ride the debounce. Will release a new version tonight. Thanks anyway for the contribution.

**Comment by stefanbuck** [comment]
Done https://github.com/octo-linker/injection/releases/tag/v0.2.0

**Pull request closed without merging**
